"""adjusted user restaurant notes table

Revision ID: 2d9753fe4bd2
Revises: 51aebba8ea64
Create Date: 2025-11-17 19:07:31.119268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9753fe4bd2'
down_revision: Union[str, Sequence[str], None] = '51aebba8ea64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_restaurant_notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('user_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('date_visited', sa.String(length=20), nullable=True),
    sa.Column('favorite_dish', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant_info.restaurant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_restaurant_notes')
    # ### end Alembic commands ###
