"""initial schema

Revision ID: 512815ed5382
Revises: 
Create Date: 2025-10-31 09:36:43.744671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512815ed5382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_info',
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('price_range', sa.String(length=20), nullable=True),
    sa.Column('rest_name', sa.String(length=100), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('loc', sa.String(length=255), nullable=False),
    sa.Column('main_photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('folders',
    sa.Column('folder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('restaurant_folders',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.folder_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant_info.restaurant_id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_folders')
    op.drop_table('folders')
    op.drop_table('users')
    op.drop_table('restaurant_info')
    # ### end Alembic commands ###
